"""site_content_and_public_fields

Revision ID: 2a9eb32c2c56
Revises: 4370257db015
Create Date: 2026-07-05 18:56:45.437716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9eb32c2c56'
down_revision: Union[str, None] = '4370257db015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_contents',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('youtube_url', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_contents_slug'), 'site_contents', ['slug'], unique=True)
    op.add_column('schools', sa.Column('cover_image_url', sa.String(length=1000), nullable=True))
    op.add_column('schools', sa.Column('long_description', sa.Text(), nullable=True))
    op.add_column('schools', sa.Column('youtube_url', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('display_order', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('is_featured_instructor', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_featured_instructor')
    op.drop_column('users', 'display_order')
    op.drop_column('users', 'bio')
    op.drop_column('schools', 'youtube_url')
    op.drop_column('schools', 'long_description')
    op.drop_column('schools', 'cover_image_url')
    op.drop_index(op.f('ix_site_contents_slug'), table_name='site_contents')
    op.drop_table('site_contents')
    # ### end Alembic commands ###
