"""add_instagram_url_to_user

Revision ID: 859ad2d0532c
Revises: 2a9eb32c2c56
Create Date: 2026-07-05 19:35:42.967985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859ad2d0532c'
down_revision: Union[str, None] = '2a9eb32c2c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('instagram_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'instagram_url')
    # ### end Alembic commands ###
