"""site_content_slug_not_unique

Revision ID: aad8091cba1c
Revises: 859ad2d0532c
Create Date: 2026-07-16 16:52:25.305517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad8091cba1c'
down_revision: Union[str, None] = '859ad2d0532c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_site_contents_slug', table_name='site_contents')
    op.create_index(op.f('ix_site_contents_slug'), 'site_contents', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_contents_slug'), table_name='site_contents')
    op.create_index('ix_site_contents_slug', 'site_contents', ['slug'], unique=True)
    # ### end Alembic commands ###
